User Defined Timestamp APIs
linxGnu/grocksdb pull request #77
Opened 2022-07-24 11:45 UTC by muthukrishnan24

Adds bindings for User Defined Timestamp APIs

2022-07-27 03:42 UTC, muthukrishnan24 commented
@linxGnu

2022-07-28 15:25 UTC, linxGnu commented
I am sorry for late reply due to my job. I will take a look and feedback soon.

thank you for the contribution

2022-08-01 07:28 UTC, linxGnu requested changes

2022-08-01 07:28 UTC, linxGnu commented on db.go
> +	return err
```go
return err
```
->
```go
return // no argument
```

2022-08-01 07:28 UTC, linxGnu commented on db.go
> +	return slice, err
ditto

2022-08-01 07:28 UTC, linxGnu commented on iterator.go
> +	return &Slice{cTs, cLen, true}
How about init with field name:
```go
return &Slice{
   field1: ... 
   field2: ...
```

2022-08-01 07:28 UTC, linxGnu commented on options_compaction.go
> +	fullHistoryTsLow []byte
How about removing this field. Seem like we do not need to track this. Its invoker (caller) responsibility

2022-08-01 07:28 UTC, linxGnu commented on transaction.go
> +func (transaction *Transaction) SetCommitTimestamp(ts uint64) {
Please add comment for this

2022-08-01 07:28 UTC, linxGnu commented on transaction.go
> +func (transaction *Transaction) SetReadTimestampForValidation(ts uint64) {
Please add comment for this

2022-08-02 09:27 UTC, muthukrishnan24 commented
Made the requested changes. Please check @linxGnu

2022-08-04 05:56 UTC, linxGnu requested changes

2022-08-04 05:58 UTC, linxGnu commented
@muthukrishnan24 

Almost LGTM, just 2 request changes above.

And could you please add more `tests`. It's important to ensure ops with timestamp works. AFAIK, `timestamp` feature is currently under experiment?

2022-08-04 07:02 UTC, muthukrishnan24 commented
> AFAIK, timestamp feature is currently under experiment?

taken from [here](https://groups.google.com/g/rocksdb/c/1_IWk1lf7GE)
 ```
It's still experimental in the sense that:

    - it's currently supported in a subset of RocksDB features: Get, Put, WriteBatch (with only Put and Delete), Delete, Iterator, basic Garbage collection not necessarily the most efficient implementation), and
    - new APIs and/or options may be added, and
    - (less likely) existing user-defined timestamp APIs and/or options are also subject to change in future RocksDB releases
```

2022-08-04 07:34 UTC, linxGnu commented
@muthukrishnan24 thank you for the info.

could you please fix my comments above and especially: adding tests

2022-08-07 11:16 UTC, muthukrishnan24 commented
Fixed your comments, Added test cases. Please change @linxGnu

2022-08-08 03:04 UTC, linxGnu approved these changes

2022-08-08 03:05 UTC, linxGnu commented
Its absolutely great job @muthukrishnan24 
I will merge your PR and prepare for next release.

2022-08-08 03:05 UTC, merged